spring.application.name=deploy
server.port=8088

# Koneksi Database (Pastikan Nama DB sama dengan saat docker run)
spring.datasource.url=jdbc:postgresql://db-mhs:5432/postgres
spring.datasource.username=praktikum-user
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Biarkan Spring Boot memilih Dialect sendiri (lebih aman)
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect